import {
  RaviPort,
  RaviPort2,
  youtubeClone,
  education,
  grocery,
  hospital,
  landing,
  shabPort,
  myPort,
  movie,
  crypto,
  music,
  admin,
  landingStory,
  Photography,
} from "../assets";

export const portfolio = [
  {
    id: 1,
    title: "Youtube Clone",
    type: "react",
    desc: "website Build using React and compaitable for Mobile and tablet screen",
    imageUrl: youtubeClone,
    webUrl: "https://youtubemy.netlify.app/",
  },
  {
    id: 2,
    title: "My Portfolio",
    type: "react",
    desc: "website Build using React and compaitable for Mobile and tablet screen",
    imageUrl: myPort,
    webUrl: "https://noushadansari.netlify.app",
  },
  {
    id: 3,
    title: "Crypto Website",
    type: "react",
    desc: "website Build using React and compaitable for Mobile and tablet screen",
    imageUrl: crypto,
    webUrl: "https://myfirstcrypto.netlify.app/",
  },

  {
    id: 4,
    title: "Portfolio",
    type: "html/css",
    desc: "website Build using Html, css and javascript for Mobile and tablet screen",
    imageUrl: RaviPort,
    webUrl: "https://noushad96.github.io/Ravi-Portfolio/",
  },
  {
    id: 5,
    title: "Portfolio",
    type: "js",
    desc: "website Build using Html, css and javascript for Mobile and tablet screen",
    imageUrl: RaviPort2,
    webUrl: "https://noushad96.github.io/RaviPortfolio2/",
  },

  {
    id: 6,
    title: "Movie Website",
    type: "react",
    desc: "website Build using React and compaitable for Mobile and tablet screen",
    imageUrl: movie,
    webUrl: "https://moviereactmy.netlify.app/",
  },

  {
    id: 7,
    title: "Educational Website",
    type: "js",
    desc: "website Build using Html, css and javascript",
    imageUrl: education,
    webUrl: "https://noushad96.github.io/Educational/",
  },
  {
    id: 8,
    title: "Grocery Website Design",
    type: "js",
    desc: "website Build using Html, css and javascript",
    imageUrl: grocery,
    webUrl: "https://noushad96.github.io/MyGrofer/",
  },
  {
    id: 9,
    title: "Medical Website",
    type: "js",
    desc: "Built a beautiful Hospital website using Html CSS and Javascript ,Font-awesome for icons",
    imageUrl: hospital,
    webUrl: "https://noushad96.github.io/Hospital-FrontEnd/",
  },
  {
    id: 10,
    title: "Landing Page Design",
    type: "js",
    desc: "Built a beautiful landing page using Html CSS and Javascript and for animation GSAP",
    imageUrl: landing,
    webUrl: "https://noushad96.github.io/Landing-Page/",
  },
  {
    id: 11,
    title: "Portfolio Design",
    type: "js",
    desc: "website Build using Html, css and javascript",
    imageUrl: shabPort,
    webUrl: "https://noushad96.github.io/shabaj-portfolio/",
  },
  {
    id: 12,
    title: "Music Player",
    type: "js",
    desc: "Beutiful website Build using Html, css and javascript",
    imageUrl: music,
    webUrl: "https://noushad96.github.io/Music-Player/",
  },
  {
    id: 13,
    title: "Landing Page Design",
    type: "html/css",
    desc: "website Build using HTML and Css only with static data",
    imageUrl: landingStory,
    webUrl: "https://noushad96.github.io/Landing-Page-Story/",
  },
  {
    id: 14,
    title: "Admin Page Design",
    type: "html/css",
    desc: "website Build using HTML and Css only with static data",
    imageUrl: admin,
    webUrl: "https://noushad96.github.io/Admin-Panel/",
  },
  {
    id: 15,
    title: "Photography Website",
    type: "js",
    desc: "website Build using HTML, Css and javascript for Mobile and tablet screen",
    imageUrl: Photography,
    webUrl: "https://noushad96.github.io/Photography/",
  },
];
